server:
  shutdown: graceful
  port: 8081
  servlet:
    context-path: /api

spring:
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_URL}/realms/access

logging:
  level:
    org.springframework:
      security: debug
      web.filter.CommonsRequestLoggingFilter: debug
