server:
  shutdown: graceful
  port: 8081
  servlet:
    context-path: /api

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/access}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

keycloak:
  realm: access
  resource: access-backend
  auth-server-url: ${AUTH_SERVER_URL:http://localhost:8080}
  bearer-only: true
  principal-attribute: email
